service: gruppo-1-minibankapi
image: KEKKOSECCI/gruppo-1-minibankapi

servers:
  web:
    - 89.167.48.93

registry:
  server: docker.io
  username: KEKKOSECCI
  password: KAMAL_REGISTRY_PASSWORD

accessories:
  db:
    image: mariadb:10.11
    host: 89.167.48.93
    port: 3306
    env:
      MYSQL_DATABASE: api_db
      MYSQL_USER: user_api
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: MYSQL_PASSWORD
    directories:
      - /var/lib/mysql:/var/lib/mysql

env:
  clear:
    DB_HOST: db
    DB_NAME: api_db
    DB_USER: user_api
  secret:
    - DB_PASS

builder:
  dockerfile: php/Dockerfile.php
  context: .
  arch: amd64

proxy:
  host: 89.167.48.93
  app_port: 80